import type { Metadata } from "next"
import "./globals.css"
import { Header } from "@/components"
import { nunito } from "./fonts/nunito"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={`${nunito.variable} antialiased bg-[#FFBF9B]`}>
                <Header />
                {children}
            </body>
        </html>
    )
}
